################################################################################
#' Plot alpha diversity, flexibly with ggplot2
#'
#' There are many useful examples of alpha-diversity graphics in the
#' \href{http://joey711.github.io/phyloseq/plot_richness-examples}{phyloseq online tutorials}.
#' This function estimates a number of alpha-diversity metrics using the 
#' \code{\link{estimate_richness}} function,
#' and returns a \code{ggplot} plotting object. 
#' The plot generated by this function will include every sample
#' in \code{physeq}, but they can be further grouped on the horizontal axis
#' through the argument to \code{x}, 
#' and shaded according to the argument to \code{color} (see below).
#' You must use untrimmed, non-normalized count data for meaningful results, 
#' as many of these estimates are highly dependent on the number of singletons.
#' You can always trim the data later on if needed,
#' just not before using this function.
#'
#'  NOTE: Because this plotting function incorporates the output from 
#'  \code{\link{estimate_richness}}, the variable names of that output should
#'  not be used as \code{x} or \code{color} (even if it works, the resulting
#'  plot might be kindof strange, and not the intended behavior of this function).
#'  The following are the names you will want to avoid using in \code{x} or \code{color}:
#'
#'  \code{c("Observed", "Chao1", "ACE", "Shannon", "Simpson", "InvSimpson", "Fisher")}.
#' 
#' @param physeq (Required). \code{\link{phyloseq-class}}, or alternatively, 
#'  an \code{\link{otu_table-class}}. The data about which you want to estimate.
#'
#' @param x (Optional). A variable to map to the horizontal axis. The vertical
#'  axis will be mapped to the alpha diversity index/estimate
#'  and have units of total taxa, and/or index value (dimensionless).
#'  This parameter (\code{x}) can be either a character string indicating a
#'  variable in \code{sample_data} 
#'  (among the set returned by \code{sample_variables(physeq)} );
#'  or a custom supplied vector with length equal to the number of samples
#'  in the dataset (nsamples(physeq)).
#'
#'  The default value is \code{"samples"}, which will map each sample's name
#'  to a separate horizontal position in the plot.
#'
#' @param color (Optional). Default \code{NULL}. 
#'  The sample variable to map to different colors.
#'  Like \code{x}, this can be a single character string of the variable name in 
#'  \code{sample_data} 
#'  (among the set returned by \code{sample_variables(physeq)} );
#'  or a custom supplied vector with length equal to the number of samples
#'  in the dataset (nsamples(physeq)).
#'  The color scheme is chosen automatically by \code{link{ggplot}},
#'  but it can be modified afterward with an additional layer using
#'  \code{\link[ggplot2]{scale_color_manual}}.
#'
#' @param shape (Optional). Default \code{NULL}. The sample variable to map
#'  to different shapes. Like \code{x} and \code{color},
#'  this can be a single character string 
#'  of the variable name in 
#'  \code{sample_data} 
#'  (among the set returned by \code{sample_variables(physeq)} );
#'  or a custom supplied vector with length equal to the number of samples
#'  in the dataset (nsamples(physeq)).
#'  The shape scale is chosen automatically by \code{link{ggplot}},
#'  but it can be modified afterward with an additional layer using
#'  \code{\link[ggplot2]{scale_shape_manual}}.
#'
#' @param title (Optional). Default \code{NULL}. Character string.
#'  The main title for the graphic.
#'
#' @param scales (Optional). Default \code{"free_y"}.
#'  Whether to let vertical axis have free scale that adjusts to
#'  the data in each panel.
#'  This argument is passed to \code{\link[ggplot2]{facet_wrap}}.
#'  If set to \code{"fixed"}, a single vertical scale will
#'  be used in all panels. This can obscure values if the
#'  \code{measures} argument includes both 
#'  richness estimates and diversity indices, for example.
#'  
#' @param nrow (Optional). Default is \code{1},
#'  meaning that all plot panels will be placed in a single row,
#'  side-by-side. 
#'  This argument is passed to \code{\link[ggplot2]{facet_wrap}}.
#'  If \code{NULL}, the number of rows and columns will be 
#'  chosen automatically (wrapped) based on the number of panels
#'  and the size of the graphics device.
#'
#' @param measures (Optional). Default is \code{NULL}, meaning that
#'  all available alpha-diversity measures will be included in plot panels.
#'  Alternatively, you can specify one or more measures
#'  as a character vector of measure names.
#'  Values must be among those supported:
#'  \code{c("Observed", "Chao1", "ACE", "Shannon", "Simpson", "InvSimpson", "Fisher")}.
#'
#' @param sortby (Optional). A character string subset of \code{measures} argument.
#'  Sort x-indices by the mean of one or more \code{measures},
#'  if x-axis is mapped to a discrete variable.
#'  Default is \code{NULL}, implying that a discrete-value horizontal axis
#'  will use default sorting, usually alphabetic.
#'  
#'  @param comparisons default NULL. example list( c("Up", "Down"), c("Up", "All") )
#'  @param stat.method wilcox.test or t.test
#'  @plottype violin or boxplot
#'
#' @return A \code{\link{ggplot}} plot object summarizing
#'  the richness estimates, and their standard error.
#' 
#' @seealso 
#'  \code{\link{estimate_richness}}
#'  
#'  \code{\link[vegan]{estimateR}}
#'  
#'  \code{\link[vegan]{diversity}}
#'
#' There are many more interesting examples at the
#' \href{http://joey711.github.io/phyloseq/plot_richness-examples}{phyloseq online tutorials}.
#'
#' 
#' @import reshape2
#' 
#' @importFrom plyr is.discrete
#' 
#' @importFrom ggplot2 geom_errorbar
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 element_text
#' @importFrom ggpubr ggboxplot stat_compare_means ggviolin
#' 
#' @export
#' @examples 
#' ## There are many more interesting examples at the phyloseq online tutorials.
#' ## http://joey711.github.io/phyloseq/plot_richness-examples
#' data("soilrep")
#' plot_alpha_boxplot(soilrep, "Treatment", "warmed", measures=c("Chao1", "ACE", "InvSimpson"), nrow=3)
#' data("GlobalPatterns")
#' plot_alpha_boxplot(GlobalPatterns, x="SampleType", measures=c("InvSimpson"))
#' plot_alpha_boxplot(GlobalPatterns, x="SampleType", measures=c("Chao1", "ACE", "InvSimpson"), nrow=3)
#' plot_alpha_boxplot(GlobalPatterns, x="SampleType", measures=c("Chao1", "ACE", "InvSimpson"), nrow=3, sortby = "Chao1")

plot_alpha = function(physeq, x="samples", color=NULL, shape=NULL, title=NULL,
                         scales="free_y", nrow=1, measures=NULL, sortby=NULL, 
                         comparisons=NULL, stat.method="wilcox.test",
                      plottype="violin"){ 
    # Calculate the relevant alpha-diversity measures
    erDF = estimate_richness(physeq, split=TRUE, measures=measures)
    # Measures may have been renamed in `erDF`. Replace it with the name from erDF
    measures = colnames(erDF)
    # Define "measure" variables and s.e. labels, for melting.
    ses = colnames(erDF)[grep("^se\\.", colnames(erDF))]
    # Remove any S.E. from `measures`
    measures = measures[!measures %in% ses]
    # Make the plotting data.frame.
    # This coerces to data.frame, required for reliable output from reshape2::melt()
    if( !is.null(sample_data(physeq, errorIfNULL=FALSE)) ){
        # Include the sample data, if it is there.
        DF <- data.frame(erDF, sample_data(physeq))
    } else {
        # If no sample data, leave it out.
        DF <- data.frame(erDF)
    }
    if( !"samples" %in% colnames(DF) ){
        # If there is no "samples" variable in DF, add it
        DF$samples <- sample_names(physeq)
    }
    # sample_names used to be default, and should also work.
    # #backwardcompatibility
    if( !is.null(x) ){
        if( x %in% c("sample", "samples", "sample_names", "sample.names") ){
            x <- "samples"
        }
    } else {
        # If x was NULL for some reason, set it to "samples"
        x <- "samples"
    }
    # melt to display different alpha-measures separately
    mdf = reshape2::melt(DF, measure.vars=measures)
    # Initialize the se column. Helpful even if not used.
    mdf$se <- NA_integer_
    if( length(ses) > 0 ){
        ## Merge s.e. into one "se" column
        # Define conversion vector, `selabs`
        selabs = ses
        # Trim the "se." from the names
        names(selabs) <- substr(selabs, 4, 100)
        # Make first letter of selabs' names uppercase
        substr(names(selabs), 1, 1) <- toupper(substr(names(selabs), 1, 1))
        # use selabs conversion vector to process `mdf`
        mdf$wse <- sapply(as.character(mdf$variable), function(i, selabs){selabs[i]}, selabs)
        for( i in 1:nrow(mdf) ){
            if( !is.na(mdf[i, "wse"]) ){
                mdf[i, "se"] <- mdf[i, (mdf[i, "wse"])]
            }
        }
        # prune the redundant columns
        mdf <- mdf[, -which(colnames(mdf) %in% c(selabs, "wse"))]
    }
    ## Interpret measures
    # If not provided (default), keep all 
    if( !is.null(measures) ){
        if( any(measures %in% as.character(mdf$variable)) ){
            # If any measures were in mdf, then subset to just those.
            mdf <- mdf[as.character(mdf$variable) %in% measures, ]
        } else {
            # Else, print warning about bad option choice for measures, keeping all.
            warning("Argument to `measures` not supported. All alpha-diversity measures (should be) included in plot.")
        }
    }

    # Address `sortby` argument
    if(!is.null(sortby)){
        if(!all(sortby %in% levels(mdf$variable))){
            warning("`sortby` argument not among `measures`. Ignored.")
        }
        if(!is.discrete(mdf[, x])){
            warning("`sortby` argument provided, but `x` not a discrete variable. `sortby` is ignored.")
        }
        if(all(sortby %in% levels(mdf$variable)) & is.discrete(mdf[, x])){
            # Replace x-factor with same factor that has levels re-ordered according to `sortby`
            wh.sortby = which(mdf$variable %in% sortby)
            mdf[, x] <- factor(mdf[, x],
                               levels = names(sort(tapply(X = mdf[wh.sortby, "value"],
                                                          INDEX = mdf[wh.sortby, x],
                                                          mean,
                                                          na.rm=TRUE, simplify = TRUE))))
        }
    }
    # Define variable mapping
    richness_map = aes_string(x=x, y="value", colour=color, shape=shape)
    # Make the ggplot.
    if (plottype=="boxplot") {
        p = ggpubr::ggboxplot(mdf, x=x, y="value", fill=x)
    } else if (plottype=="violin") {
        p = ggpubr::ggviolin(mdf, x=x, y="value", fill=x, scale = "count", 
                             draw_quantiles = c(0.25, 0.5, 0.75) ) 
    }
    
    if (!is.null(comparisons) ) {
        # http://www.sthda.com/english/articles/24-ggpubr-publication-ready-plots/76-add-p-values-and-significance-levels-to-ggplots/
        p <- p + ggpubr::stat_compare_means( comparisons=comparisons, method = stat.method)
    }
    
    # Add error bars if mdf$se is not all NA
    # if( any(!is.na(mdf[, "se"])) ){
    #     p = p + geom_errorbar(aes(ymax=value + se, ymin=value - se), width=0.1) 
    # }
    # Rotate horizontal axis labels, and adjust
    p = p + theme(axis.text.x=element_text(angle=-90, vjust=0.5, hjust=0))
    # Add y-label 
    p = p + ylab('Alpha Diversity Measure') 
    # Facet wrap using user-options
    p = p + facet_wrap(~variable, nrow=nrow, scales=scales)
    # Optionally add a title to the plot
    if( !is.null(title) ){
        p <- p + ggtitle(title)
    }
    
    return(p)
}
